[terminal]
shell = { program = "C:/Program Files/PowerShell/7/pwsh.exe"}

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
dynamic_padding = false
opacity = 0.9
padding = { x = 25, y = 20 }
title = "Alacritty"
dynamic_title = false

[font]
size = 14.0
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
bold = { family = "JetBrainsMono Nerd Font", style = "Heavy" }
italic = { family = "JetBrainsMono Nerd Font", style = "Medium Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Heavy Italic" }

[general]
working_directory = "C:/Users/jordi"
live_config_reload = true
import = ["~/AppData/Roaming/alacritty/rose-pine-moon.toml"]

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" } # Shape: Block, Beam, Underline
unfocused_hollow = true

[scrolling]
history = 10000
multiplier = 1

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
]
